# Generated by Django 4.2.7 on 2026-01-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'note_chapters',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=550)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_drive_sync_at', models.DateTimeField(blank=True, null=True)),
                ('upload_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicCodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('csharp', 'C#'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('other', 'Other')], default='python', max_length=50)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_code_snippets',
            },
        ),
        migrations.CreateModel(
            name='TopicExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_explanations',
            },
        ),
        migrations.CreateModel(
            name='TopicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic_sources',
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Read Only'), ('edit', 'Can Edit')], default='view', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notes.note')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='notes.chapter')),
                ('code_snippet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='notes.topiccodesnippet')),
                ('explanation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='notes.topicexplanation')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='notes.topicsource')),
            ],
            options={
                'db_table': 'chapter_topics',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='notes.note'),
        ),
        migrations.CreateModel(
            name='AIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('explain_topic', 'AI Explain Topic'), ('improve', 'AI Improve'), ('summarize', 'AI Summarize'), ('generate_code', 'AI Generate Code')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('input_content', models.TextField(blank=True)),
                ('generated_content', models.TextField()),
                ('language', models.CharField(blank=True, default='python', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('generate_explanation', 'Generate Explanation'), ('improve_explanation', 'Improve Explanation'), ('summarize_explanation', 'Summarize Explanation'), ('generate_code', 'Generate Code')], max_length=50)),
                ('input_content', models.TextField()),
                ('generated_content', models.TextField()),
                ('model_used', models.CharField(default='llama-3.3-70b-versatile', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='notes.chaptertopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_generated_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('changes_summary', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.note')),
            ],
            options={
                'db_table': 'note_versions',
                'ordering': ['-version_number'],
                'unique_together': {('note', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='notes_user_id_8a4da1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'status'], name='notes_user_id_90ed5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_note_title'),
        ),
        migrations.AddConstraint(
            model_name='chaptertopic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chaptertopic',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='unique_topic_order_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('note', 'title'), name='unique_chapter_per_note'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('note', 'order'), name='unique_chapter_order_per_note'),
        ),
        migrations.AddIndex(
            model_name='aihistory',
            index=models.Index(fields=['user', '-created_at'], name='ai_history_user_id_51e006_idx'),
        ),
        migrations.AddIndex(
            model_name='aihistory',
            index=models.Index(fields=['user', 'feature_type'], name='ai_history_user_id_af498c_idx'),
        ),
    ]
