# Generated by Django 5.1.3 on 2026-02-03 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='note_user_updated_idx',
            old_name='notes_user_id_8a4da1_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='note_user_status_idx',
            old_name='notes_user_id_90ed5e_idx',
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status', '-created_at'], name='note_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='note_created_idx'),
        ),
    ]
