# Generated by Django 4.2.8 on 2026-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_notes_user_id_8a4da1_idx_note_user_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aigeneratedcontent',
            index=models.Index(fields=['user', '-created_at'], name='ai_gen_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aigeneratedcontent',
            index=models.Index(fields=['topic', '-created_at'], name='ai_gen_topic_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aigeneratedcontent',
            index=models.Index(fields=['user', 'action_type'], name='ai_gen_user_action_idx'),
        ),
        migrations.AddIndex(
            model_name='noteshare',
            index=models.Index(fields=['note', '-created_at'], name='share_note_date_idx'),
        ),
        migrations.AddIndex(
            model_name='noteshare',
            index=models.Index(fields=['shared_with', '-created_at'], name='share_recipient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='noteshare',
            index=models.Index(fields=['public_slug'], name='share_public_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='noteshare',
            index=models.Index(fields=['is_public', 'expires_at'], name='share_public_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='noteversion',
            index=models.Index(fields=['note', '-version_number'], name='version_note_number_idx'),
        ),
        migrations.AddIndex(
            model_name='noteversion',
            index=models.Index(fields=['note', '-saved_at'], name='version_note_date_idx'),
        ),
    ]
