# Generated by Django 5.1.3 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('active_users_week', models.IntegerField(default=0)),
                ('active_users_month', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('new_users_week', models.IntegerField(default=0)),
                ('total_notes', models.IntegerField(default=0)),
                ('total_chapters', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('published_notes', models.IntegerField(default=0)),
                ('draft_notes', models.IntegerField(default=0)),
                ('total_ai_requests', models.IntegerField(default=0)),
                ('ai_requests_today', models.IntegerField(default=0)),
                ('ai_requests_week', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('avg_topics_per_note', models.FloatField(default=0)),
                ('avg_chapters_per_note', models.FloatField(default=0)),
                ('user_engagement_rate', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_statistics',
                'get_latest_by': 'calculated_at',
            },
        ),
    ]
