# Generated by Django 4.2.7 on 2026-01-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginactivity_device_type_profile_total_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_completed',
        ),
    ]
