# Generated by Django 4.2.7 on 2026-01-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
