# Generated by Django 4.2.8 on 2026-02-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plan', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20)),
                ('daily_ai_limit', models.IntegerField(default=10)),
                ('weekly_ai_limit', models.IntegerField(default=50)),
                ('monthly_ai_limit', models.IntegerField(default=200)),
                ('can_use_ai_tools', models.BooleanField(default=True)),
                ('can_export_pdf', models.BooleanField(default=True)),
                ('can_publish_notes', models.BooleanField(default=True)),
                ('max_notes', models.IntegerField(default=100)),
                ('max_storage_mb', models.IntegerField(default=500)),
                ('ai_requests_today', models.IntegerField(default=0)),
                ('ai_requests_week', models.IntegerField(default=0)),
                ('ai_requests_month', models.IntegerField(default=0)),
                ('last_reset_daily', models.DateField(default=django.utils.timezone.now)),
                ('last_reset_weekly', models.DateField(default=django.utils.timezone.now)),
                ('last_reset_monthly', models.DateField(default=django.utils.timezone.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user plan',
                'verbose_name_plural': 'user plans',
                'db_table': 'user_plans',
                'indexes': [models.Index(fields=['plan_type'], name='plan_type_idx'), models.Index(fields=['is_blocked'], name='plan_blocked_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'Block User'), ('unblock', 'Unblock User'), ('change_plan', 'Change Plan'), ('change_limits', 'Change Limits'), ('revoke_access', 'Revoke Access'), ('grant_access', 'Grant Access'), ('reset_usage', 'Reset Usage'), ('send_notification', 'Send Notification')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user action log',
                'verbose_name_plural': 'user action logs',
                'db_table': 'user_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='action_user_date_idx'), models.Index(fields=['admin', '-created_at'], name='action_admin_date_idx'), models.Index(fields=['action'], name='action_type_idx')],
            },
        ),
    ]
