# Generated by Django 4.2.8 on 2026-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userplan_useractionlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='email_verification_token_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', '-created_at'], name='email_verif_u_date_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['verified', 'expires_at'], name='email_verification_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', '-login_at'], name='login_activity_u_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['-login_at'], name='login_activity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['ip_address'], name='login_activity_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['token'], name='password_reset_token_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['user', '-created_at'], name='pw_reset_u_date_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['used', 'expires_at'], name='password_reset_valid_idx'),
        ),
    ]
