# Generated by Django 5.2.1 on 2026-02-12 13:57

from django.db import migrations, connection


def create_cache_table(apps, schema_editor):
    """Create Django cache table with database-specific SQL."""
    from django.db import connection
    
    db_vendor = connection.settings_dict.get('ENGINE', '').split('.')[-1]
    
    with connection.cursor() as cursor:
        # Check if table already exists
        try:
            cursor.execute("SELECT 1 FROM django_cache_table LIMIT 1")
            return  # Table already exists
        except Exception:
            pass
        
        # Create table based on database
        if 'postgres' in db_vendor:
            # PostgreSQL
            sql = """
            CREATE TABLE IF NOT EXISTS django_cache_table (
                cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
                value BYTEA,
                expires BIGINT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS django_cache_table_expires ON django_cache_table (expires);
            """
        else:
            # SQLite and others
            sql = """
            CREATE TABLE IF NOT EXISTS django_cache_table (
                cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
                value BLOB,
                expires INTEGER NOT NULL
            );
            CREATE INDEX IF NOT EXISTS django_cache_table_expires ON django_cache_table (expires);
            """
        
        for statement in sql.strip().split(';'):
            if statement.strip():
                cursor.execute(statement)


def reverse_cache_table(apps, schema_editor):
    """Drop cache table."""
    with connection.cursor() as cursor:
        try:
            cursor.execute("DROP TABLE IF EXISTS django_cache_table")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverification_email_verification_token_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_cache_table, reverse_cache_table),
    ]
