# Generated by Django 5.2.1 on 2026-02-12 13:57

from django.db import migrations


def create_cache_table(apps, schema_editor):
    """Create Django cache table using Django's management command."""
    from django.core.management import call_command
    from django.db import connection
    
    # Get the database alias
    db_alias = schema_editor.connection.alias
    
    # Check if table already exists
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT 1 FROM django_cache_table LIMIT 1")
        except Exception:
            # Table doesn't exist, create it
            try:
                call_command('createcachetable', database=db_alias, verbosity=0)
            except Exception:
                # Fallback: create table manually using SQL
                if 'postgres' in connection.settings_dict.get('ENGINE', ''):
                    sql = """
                    CREATE TABLE IF NOT EXISTS django_cache_table (
                        cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
                        value BYTEA,
                        expires BIGINT NOT NULL
                    );
                    CREATE INDEX IF NOT EXISTS django_cache_table_expires ON django_cache_table (expires);
                    """
                else:
                    sql = """
                    CREATE TABLE IF NOT EXISTS django_cache_table (
                        cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
                        value BLOB,
                        expires INTEGER NOT NULL
                    );
                    CREATE INDEX IF NOT EXISTS django_cache_table_expires ON django_cache_table (expires);
                    """
                with connection.cursor() as c:
                    for statement in sql.split(';'):
                        if statement.strip():
                            c.execute(statement)


def reverse_func(apps, schema_editor):
    """Drop cache table."""
    from django.db import connection
    with connection.cursor() as cursor:
        try:
            cursor.execute("DROP TABLE IF EXISTS django_cache_table CASCADE")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverification_email_verification_token_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_cache_table, reverse_func),
    ]
