# Generated by Django 4.2.7 on 2026-01-21 11:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, help_text='Brief biography (max 2000 characters)', max_length=2000)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (max 5MB, jpg/png/webp)', null=True, upload_to='avatars/', validators=[profiles.models.validate_image_size])),
                ('learning_goal', models.TextField(blank=True, help_text='What you want to achieve', max_length=1000)),
                ('preferred_study_hours', models.IntegerField(default=2, help_text='Preferred daily study hours (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('timezone', models.CharField(choices=[('America/New_York', 'Eastern Time (ET)'), ('America/Chicago', 'Central Time (CT)'), ('America/Denver', 'Mountain Time (MT)'), ('America/Los_Angeles', 'Pacific Time (PT)'), ('UTC', 'UTC'), ('Europe/London', 'London (GMT)'), ('Europe/Paris', 'Central European Time'), ('Asia/Dubai', 'Dubai (GST)'), ('Asia/Karachi', 'Pakistan (PKT)'), ('Asia/Kolkata', 'India (IST)'), ('Asia/Shanghai', 'China (CST)'), ('Asia/Tokyo', 'Japan (JST)'), ('Australia/Sydney', 'Sydney (AEDT)')], default='UTC', max_length=50)),
                ('skill_interests', models.JSONField(blank=True, default=list, help_text='List of skills you are interested in', validators=[profiles.models.validate_skill_interests])),
                ('total_study_days', models.IntegerField(default=0, editable=False)),
                ('current_streak', models.IntegerField(default=0, editable=False)),
                ('longest_streak', models.IntegerField(default=0, editable=False)),
                ('total_notes', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_settings', serialize=False, to='profiles.profile')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for important updates')),
                ('weekly_summary', models.BooleanField(default=True, help_text='Receive weekly summary of learning progress')),
                ('course_reminders', models.BooleanField(default=True, help_text='Receive reminders about active courses')),
                ('achievement_alerts', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='ProfileActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('profile_updated', 'Profile Updated'), ('avatar_changed', 'Avatar Changed'), ('password_changed', 'Password Changed'), ('preferences_updated', 'Preferences Updated'), ('notifications_updated', 'Notifications Updated')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'profile_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
