# Generated by Django 4.2.8 on 2026-02-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_course_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='study_reminders',
            field=models.BooleanField(default=True, help_text='Receive reminders about active study notes'),
        ),
    ]
